print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10 12 15 "))
people = int(input("How many people to split the bill? "))
a = float(bill * ( tip / 100))
b= float((bill + a ) / people)
print ("Each person should pay: $" + str(b))